[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "Meslo LG M DZ for Powerline"
style = "Bold"

[font.bold_italic]
family = "Meslo LG M DZ for Powerline"
style = "bold_italic"

[font.italic]
family = "Meslo LG M DZ for Powerline"
style = "italic"

[font.normal]
family = "Meslo LG M DZ for Powerline"
style = "Regular"

[[hints.enabled]]
command = "firefox"
post_processing = true
regex = "(https:|http:|www\\.)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[selection]
save_to_clipboard = true
