# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
 min-width=300
 max-width=300
 max-height=500
# stacking-order=bottom-up
# anchor=top-right
# edge-margin-vertical=10
# edge-margin-horizontal=10
# notification-margin=10
# icon-theme=hicolor
# max-icon-size=32
# selection-helper=dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
# background=3f5f3fff

 border-color=aaaaaaff
# border-radius=0
 border-size=3

 padding-vertical=0
# padding-horizontal=20

# dpi-aware=no

# title-font=sans serif
# title-color=ffffffff
#Don't want to see the title
 title-format=<i></i>

#Main text
summary-font = Meslo LG S DZ for Powerline Regular:size=12
# summary-color=ffffffff
# summary-format=<b>%s</b>\n


body-font = Meslo LG S DZ for Powerline Regular:size=12
# body-color=ffffffff
 body-format=%b\n

# progress-bar-height=20
# progress-bar-color=ffffffff

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
 default-timeout=40
 idle-timeout=40

# [low]
# background=2b2b2bff
# title-color=888888ff
# summary-color=888888ff
# body-color=888888ff

# [normal]
background=aa0000ff

# [critical]
# background=6c3333ff
