#!/usr/bin/python3
import sys
import subprocess
'''
Format INFILE:

This is a test
If everything works as intended
$E = m^2\cdot c$
;
This works
$f(x)=2$ pretty
well

testFront
;
testBack
'''

def trimLastEmptyLines(l):
    foundNonEmpty = False
    lTmp = []
    for line in l[::-1]: #Reversed list
        if foundNonEmpty:
            lTmp.append(line)
            continue
        if not foundNonEmpty and line.strip() != "":
            foundNonEmpty = True
            lTmp.append(line)
    return lTmp[::-1] #Reverse again



if len(sys.argv) !=3:
    print("ankiParser INFILE OUTFILE\nAbort" )
    sys.exit()

IFile = sys.argv[1]
OFile = sys.argv[2]
outF = open(OFile, 'w') #Delete everything from Outfile

beforeSemi = True
firstPart=[]
secondPart=[]
allFirstParts=[]

linenum = 0
with open(IFile) as f:
    content = f.readlines()

content = trimLastEmptyLines(content)


for line in content:
    linenum+=1
    line = line.strip()

    #Normal quotes disapper when imported
    line = line.replace('"', '\\doubleq ')
    line = line.replace("'", '\\singleq ')
#        if ',' in line:
#            print("Line " + str(linenum) + ": Comma messes up import. Abort")
#            sys.exit(1)
#        elif line == ";" and beforeSemi: #First semicolon

    if line == ";" and beforeSemi: #First semicolon
        beforeSemi = False
        if firstPart in allFirstParts:
            print("Line " + str(linenum) + ": Duplicate Front of Page")
            sys.exit(1)
        continue
    elif ";" in line:
        print("Line " + str(linenum) + ": Don't use Semicolon")
        sys.exit(1)
#    elif '"' or "'" in line:
#        print("Line " + str(linenum) + ": Don't use (double) quotes, they will disappear when imported.")
#        sys.exit(1)
    elif line == "": #Just Spaces -> New Card
        if beforeSemi or firstPart == "" or secondPart == "":
            print("Line " + str(linenum) + ": Forgot semicolon/second part of card. Or two spaces after card")
            sys.exit(1)

        outF = open(OFile, 'a')
        outF.write('\\\\'.join(firstPart) + " ; " + '\\\\'.join(secondPart) + "\n")

        beforeSemi = True
        allFirstParts.append(firstPart)
        firstPart=[]
        secondPart=[]
        continue

    if beforeSemi:
        try:
            subprocess.check_output("checkValidLatexLine \'" +line.replace("'", "\"") + "\'", shell=True) #' does not crash latex, but bash argument. Therefore check with ", but original string will be appended with ' to OutFile
        except:
            print("Line " + str(linenum) + ": Not valid Latex code")
            sys.exit(1)
        firstPart.append(line)
    else:
        try:
            subprocess.check_output("checkValidLatexLine \'" +line.replace("'", "\"") + "\'", shell=True)#' does not crash latex, but bash argument. Therefore check with ", but original string will be appended with ' to OutFile
        except:
            print("Line " + str(linenum) + ": Not valid Latex code")
            sys.exit(1)
        secondPart.append(line)


if beforeSemi or firstPart == "" or secondPart == "":
    print("Line " + str(linenum) + ": Forgot semicolon/second part of card. Or two spaces after card")
    sys.exit(1)

#Last Card
outF = open(OFile, 'a')
outF.write('\\\\'.join(firstPart) + " ; " + '\\\\'.join(secondPart)+ "\n")
