#!/bin/sh
#FORMAT - Q.tex/png/jpg, QSQL.tex/png/jpg (Don't have to be same format)

set -e

MODULES="$HOME/Dokumente/Master_Berlin/3.Semester/EX"
TYPES='(tex|jpg|png)'
TASKSPERMODULE=2
OPENPIC="feh --auto-rotate -F"

openFile() {
  FILE=$1
  if [[ "$FILE" = *"tex"* ]]; then
    showLatexAsImage $FILE 
  else
    $OPENPIC $FILE
  fi
}

checkFileEnding() {
  FILE=$1
  FILEENDING=$(echo "$FILE" | sed 's/.*\.\(.*\)/\1/g')
  if [[ "$FILEENDING" != "tex" && "$FILEENDING" != "jpg" && "$FILEENDING" != "png"   ]]; then
    echo "$FILE" wrong file format
    exit 1
  fi
}

for FILE in `find $MODULES -type f`; do
  checkFileEnding "$FILE"
  if [[ "$FILE" = *"SOL"* ]]; then #Is a Solution
    EX=$(echo "$FILE" | sed 's/SOL//') #Take out SOL
    EXFILENAME=$(echo "$FILE" | sed 's/\(.*\)SOL\.\(.*\)/\1/g')
    NUMOFEXFILES=$(ls "$EXFILENAME".* 2> /dev/null | wc -l)
    if (( $NUMOFEXFILES != 1 )); then #EX File doesn't exist
      echo "Exercise to $FILE does not exist"
      exit 1
    fi
  else #Is an Exercise
    SOLFILENAME=$(echo "$FILE" | sed 's/\(.*\)\(\..*\)/\1SOL/g')
    NUMOFSOLFILES=$(ls "$SOLFILENAME".* 2> /dev/null  | wc -l)
    if (( $NUMOFSOLFILES != 1 )); then #SOL File doesn't exist
      echo "Solution to $FILE does not exist"
      exit 1
    fi
  fi
done

#Loop over all subdirs, delete "FOLDER/" from beginnging and "/" from end
for MODULE in `ls -d $MODULES/*/ | sed 's|\(.*\)/$|\1|' `; do
  #Remove Solutions, only show tex/png/jpg files
 
  echo "MODULE:" $MODULE
  ESCAPEDMODULE=$(echo "$MODULE" | sed 's|/|\\/|g')

  EXS=$(find "$MODULE" | grep -v "SOL" | sed -n -E "/.*$ESCAPEDMODULE.*\.$TYPES$/p")
  NUMEXS=$(echo "$EXS" | wc -w) #Empty line => 1 => -w instead of -l
  if [[ "$NUMEXS" = "0" ]]; then
    continue
  fi
  for i in `seq 1 $TASKSPERMODULE`; do
    RANDOMNUM=$(( ( RANDOM % $NUMEXS )  + 1 ))
    RANDOMEX=$(echo "$EXS" | sed "${RANDOMNUM}q;d")
    echo "Current Exercise: $RANDOMEX" | sed 's| ./| |'
    openFile $RANDOMEX

    #Add SOL for finding solution + Delete Extension to be able to have differnet data types for exercise and solution
    RANDOMEXSOL=$(echo "$RANDOMEX" | sed "s/\(.*\)\(\..*\)/\1SOL/")
    openFile $RANDOMEXSOL*
  done
done
