#!/bin/bash
sudo systemctl start bluetooth.service
rfkill | sed -n 's/^ \([0-9]\) bluetooth.*/\1/p' | xargs -I{} sudo rfkill unblock {}
pulseaudio -k
(
    echo default-agent
) | sudo bluetoothctl
sleep 2
(
    echo power on
) | sudo bluetoothctl
sleep 2
(
    echo scan on
) | sudo bluetoothctl
sleep 10
(
    echo 'connect 08:EB:ED:82:1F:63'
) | sudo bluetoothctl

