#!/bin/bash
DOCKER=""
COUNT="1"
SUM=$(ls -d */ | grep -oP "\w*[A-Z]+\w*" | wc -l ) #Only directories + which start with a capital letter
REALSUM=$(($SUM + 2)) # There are (somewhere) 2 more projects

function dockersum {
    tput sc #Save cursor position
    printf "0/$REALSUM"
    while read -r line; do
#        echo "$line"
        if [[ $line == *"init"* ]]; then
            tput rc #goto last line
            tput el #Delete last line
            printf "$COUNT/$REALSUM..."
            COUNT=$(($COUNT + 1))
        fi
        if [[ $line == *"Failed"* ]]; then
            return 123
        fi
    done
}

read -p "Branch to rebase(master|develop): " BRANCH
git fetch origin

if [[ $BRANCH == "master" ]]; then
    git rebase origin/master
elif [[ $BRANCH == "develop" ]]; then
    git rebase origin/develop
else
    echo "Don't know this branch!"
fi

echo "Make Docker..."
make dockerimage > /dev/null
echo "Run Docker..."
python3 run_docker.py 2>&1 | dockersum
if [ "$?" == 123 ]; then
    echo ""
    echo "Docker: BUILD FAILED"
else
    echo ""
    echo "Docker: BUILD SUCCESSFUL"
fi
echo "Run Gradle..."
./gradlew clean test 2>&1| grep "BUILD" | awk '{print "Gradle: " $1" "$2}'
