#!/bin/bash

#HEADER/FOOTER from Anki Latex Card

OUT="/tmp/latexCheckOut"
mkdir -p $OUT
TMP=$(mktemp)
HEADER='
\documentclass[12pt]{article}
\special{papersize=3in,5in}
\usepackage[utf8]{inputenc}
\usepackage{amssymb,amsmath}
\usepackage{mathtools}
\usepackage{stmaryrd}

\usepackage{graphicx}
\graphicspath{{/home/nwuensche/saveFolder/AnkiImages/}}
\pagestyle{empty}
\setlength{\parindent}{0in}
\renewcommand{\l}{\lambda}
\newcommand{\doubleq}{"}
\newcommand{\singleq}{`}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\G}{\mathcal{G}}
\newcommand{\E}{\mathcal{E}}
\DeclarePairedDelimiter{\ceil}{\lceil}{\rceil}
\DeclarePairedDelimiter{\floor}{\lfloor}{\rfloor}

\begin{document}
'
FOOTER='
\end{document}
'
LINE=$1
echo "$HEADER">$TMP
echo "$LINE">>$TMP
echo "$FOOTER">>$TMP
pdflatex --output-directory="$OUT" --halt-on-error $TMP
