#!/bin/bash
while true; do
    sleep 300;
    SAFE=$(curl -s https://www.expressvpn.com/de/what-is-my-ip | tr "\n" ' ' | sed -n '/IP-Adresse sicher/p')
    if [ "$SAFE" == "" ]; then
        notify-send "VPN aus"
    fi
done


