#!/bin/bash
SAFE=$(curl -s https://nordvpn.com/wp-admin/admin-ajax.php\?action\=get_user_info_data | jq '.status')
if [ "$SAFE" == "false" ]; then
    echo "VPN aus"
    notify-send "VPN aus" -u low #urgency low to not show long
fi

