#!/bin/sh
#Each Rect has Size 10% of Image (Overflow possible)
#Split image in 10 rectangles, randomly color x of them
IMAGE=$1
IMAGEHEIGHT=$(file $IMAGE | sed -n 's/.*x\(\S*\),.*/\1/p')
IMAGEWIDTH=$(file $IMAGE | sed -n 's/.* \(\S*\)x.*/\1/p')
SPACE10=$(( $IMAGEWIDTH  / 10 ))
DRAW=""
USED_INDICES=""

for i in `seq 1 3`; do
  while true; do
    INDEX=$(shuf -i 0-9 -n 1)
    if [[ $USED_INDICES != *"$INDEX"* ]]; then #Not used this index
      break
    fi
  done
  USED_INDICES+=" $INDEX"
  STARTWIDTH=$(( $SPACE10 * $INDEX  ))
  ENDWIDTH=$(( $SPACE10 * ($INDEX + 1)  ))
  DRAW+="-draw \" rectangle $STARTWIDTH,0 $ENDWIDTH,$IMAGEHEIGHT \" "
done

set -x
eval "convert $IMAGE -stroke black -strokewidth 3 $DRAW rect_$IMAGE" #Need eval to fix escaped quotes from $DRAW
feh rect_$IMAGE
