#!/bin/sh
#Each Rect has Size 10% of Image (Overflow possible)
#A = (RH2-RH1) * abs ( RW2 -RW1 )
# RW2 = (A/(RH2-RH1)) + RW1
IMAGE=$1
IMAGEWIDTH=$(file $IMAGE | sed -n 's/.*x\(\S*\),.*/\1/p')
IMAGEHEIGHT=$(file $IMAGE | sed -n 's/.* \(\S*\)x.*/\1/p')
SPACE10=$(( ($IMAGEWIDTH * $IMAGEHEIGHT) /10 ))
DRAW=""

for i in `seq 1 3`; do
  RANDHEIGHT1=$(shuf -i 1-$IMAGEHEIGHT -n 1)
  RANDHEIGHT2=$(shuf -i $((RANDHEIGHT1 + 1))-$IMAGEHEIGHT -n 1)
  RANDWIDTH1=$(shuf -i 1-$IMAGEWIDTH -n 1)
  RANDWIDTH2=$(( ($SPACE10 / ($RANDHEIGHT2 - $RANDHEIGHT1)) + RANDWIDTH1 ))
  DRAW+="-draw \" rectangle $RANDHEIGHT1,$RANDWIDTH1 $RANDHEIGHT2,$RANDWIDTH2 \" "
done

eval "convert $IMAGE -stroke black -strokewidth 3 $DRAW rect_$IMAGE" #Need eval to fix escaped quotes from $DRAW
feh rect_$IMAGE
