#!/bin/bash
#https://askubuntu.com/questions/517891/bash-script-for-extracting-archives-how-to-make-the-script-ask-for-folder-dest

SCRIPTNAME="${0##*/}"

err() {
    printf >&2 "$SCRIPTNAME: $*\n"
    exit 1;
}

readF() {
  read -p "Extract to: " TARGET
  if [[ -z $TARGET ]]; then
    echo "Please Enter Folder Name"
    BADF=true
  elif [[ -e $TARGET ]]; then
    echo "Folder already exists"
    BADF=true
  else
    mkdir $TARGET
  fi;
}

BADF=false
readF
while $BADF ; do
  BADF=false
  readF
  echo $BADF
done

ARC="$1"
[[ -f $ARC ]] || err $"'$ARC' does not exist"
ARC="$(readlink -f "$ARC")"


cd "$TARGET"
case "$ARC" in
    *.tar.bz2)   tar xjf "$ARC"     ;;
    *.tar.gz)    tar xzf "$ARC"     ;;
    *.tar.xz)     tar xf "$ARC"     ;;
    *.bz2)       bunzip2 "$ARC"     ;;
    *.rar)       unrar e "$ARC"     ;;
    *.gz)        gunzip "$ARC"      ;;
    *.tar)       tar -xvf "$ARC"      ;;
    *.tbz2)      tar xjf "$ARC"     ;;
    *.tgz)       tar xzf "$ARC"     ;;
    *.zip)       unzip "$ARC"       ;;
    *.Z)         uncompress "$ARC"  ;;
    *.7z)        7z x "$ARC"        ;;
    *)           echo "'$ARC' cannot be extracted by $SCRIPTNAME" ;;
esac
