#!/bin/sh
ID=$(adb devices | sed -n '2,$ p' | sed '$ d' | awk '{print $1}' | xargs -I{} sh -c "adb -s {} shell dumpsys window | grep mDreamingLockscreen=false -q && echo {}" | head -n1 )
if [[ "$ID" == "" ]]; then
  echo "No Active Device"
 	exit 1
fi
echo $ID
