#!/bin/bash

#If fullscreen, set cursor to corner to stop xautolock from activating

function isAudioRunning() {
  #`|| true` to prevent exit 1 when grep doesn't find anything
  RUNNING=$(echo "list-sink-inputs" | pacmd | grep "state: RUNNING" || true)

  #Some audio is running
  if [[ "$RUNNING" != "" ]]; then
    echo "TRUE"
    exit 0
  fi
  echo "FALSE"
  exit 0

}

EXECUTER=$1
#Just do this for Chromium
NAMEWINDOW=$(echo $(xwininfo -id $(xdotool getactivewindow)) | sed -n -r '/(prime video|games done quick|gamesDoneQuick|youtube|ted|zdfmediathek|kyoto university opencourseware|media.ccc.de|ARD Mediathek).*(Firefox|Chromium)/Ip')
WINDOW=$(echo $(xwininfo -id $(xdotool getactivewindow) -stats | \
                egrep '(Width|Height):' | \
                awk '{print $NF}') | \
         sed -e 's/ /x/')
SCREEN=$(xdpyinfo | grep -m1 dimensions | awk '{print $2}')
if [ "$WINDOW" = "$SCREEN" ] || [ "$WINDOW" = "1916x1058" ]; then #Fullscreen or single window i3
    if [ "$NAMEWINDOW" = "" ]; then

        OLDMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        # Black
        xset dpms force standby
        sleep 30
        CURRMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        if [ "$OLDMOUSEPOS" = "$CURRMOUSEPOS" ] ; then #Fullscreen or single window i3
          #NEW i3lock
          xset dpms force on
        fi
        sleep 120
        CURRMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        AUDIORUNNING=$(isAudioRunning)
        if [ "$OLDMOUSEPOS" = "$CURRMOUSEPOS" ] && [ "$AUDIORUNNING" = "FALSE" ] ; then #Fullscreen or single window i3 and no music playing right now
#          xset dpms force on
#TODO IN          systemctl suspend 
          echo "TODO"
        fi

        #Disable doesn't reset timer
#         xautolock -enable
        #TODO Sonst evnt xautolock -restart
    fi
else
  #systemctl suspend 
        OLDMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        # Black
        xset dpms force standby
        sleep 30
        CURRMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        if [ "$OLDMOUSEPOS" = "$CURRMOUSEPOS" ] ; then #Fullscreen or single window i3
          xset s activate
          #NEW i3lock
        fi
        sleep 120
        CURRMOUSEPOS=$(xdotool getmouselocation | awk '{print $1$2}')
        AUDIORUNNING=$(isAudioRunning)
        if [ "$OLDMOUSEPOS" = "$CURRMOUSEPOS" ] && [ "$AUDIORUNNING" = "FALSE" ] ; then #Fullscreen or single window i3 and no music playing right now
          xset dpms force on
          xset s activate
          systemctl suspend 
        fi
fi
