#!/bin/bash

set -e

ACTIVE_ID=`getActiveAndroidDeviceId`
#1 is landscpae, 0 is normal
CURRROTATION=$(adb -s $ACTIVE_ID shell dumpsys input | grep 'SurfaceOrientation' | awk '{ print $2 }') 

#Disable accelerometer_rotation, otherwise adb rotation does not work
adb shell content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:0

if [[ "$CURRROTATION" == "1" ]]; then
  adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:0
elif [[ "$CURRROTATION" == "0" ]]; then
  adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:1
fi
