#!/bin/sh
IN=$(less <&0) #Read STDIN for vim
FLAG=$1
OFFSET=$2
IFS='' #Otherwise spaces at beginning are getting deleted

right(){
  while read -r LINE; do #-r does that \ not deleted
    lastNum=$(echo "$LINE" | sed -n 's/.*(\s*\(.*\)\s*,.*).*/\1/p') #INFO last because .* beginning greedy
    firstNum=$(echo "$LINE" | sed -n 's/.*(\s*\(.*\)\s*,.*).*(.*).*/\1/p') #INFO last because .* beginning greedy
    if [[ "$lastNum" == "" ]]; then 
      echo "$LINE"
      continue
    fi
    #Does not exist for nodes like text -> Skip them
    if [[ "$firstNum" == "" ]]; then 
      echo "$LINE"
      continue
    fi

    #INFO Bash cant do floating point
    #Only Change 2nd number to change size
    newSecoundNum=$(echo "$lastNum + $OFFSET" | bc )
    replaceSecoundNum=$(echo "$LINE" | sed -n "s/\(.*(\s*\)\(.*\)\(,.*).*\)/\1$newSecoundNum\3/p")

    echo "$replaceSecoundNum"
  done <<< "$IN"
}

up() {
  while read -r LINE; do #-r does that \ not deleted
    lastNum=$(echo "$LINE" | sed -n 's/.*(.*,\s*\(.*\)\s*).*/\1/p') #INFO last because .* beginning greedy
    firstNum=$(echo "$LINE" | sed -n 's/.*(.*,\s*\(.*\)\s*).*(.*).*/\1/p') #INFO last because .* beginning greedy
    if [[ "$lastNum" == "" ]]; then 
      echo "$LINE"
      continue
    fi

    #Does not exist for nodes like text
    if [[ "$firstNum" == "" ]]; then 
      echo "$LINE"
      continue
    fi
    #INFO Bash cant do floating point
    newSecoundNum=$(echo "$lastNum + $OFFSET" | bc )
    replaceSecoundNum=$(echo "$LINE" | sed -n "s/\(.*(.*,\s*\)\(.*\)\(\s*).*\)/\1$newSecoundNum\3/p")
    #TODO Right geht nicht
    echo "$replaceSecoundNum"
  done <<< "$IN"
}

case $FLAG in
  -r ) right; break;;
  -u ) up; break;;
  * ) echo "Input Format: FILE -r NUM | FILE -u NUM"
esac
