#!/bin/bash

#2 ex. Monitors -> Turn off Laptop Display
#1 ex. Monitor -> Mirror Laptop
#0 ex. Monitors -> Just show Laptop

HDMI=$( xrandr | grep "HDMI-1" | grep -v "disconnected" )
VGA=$( xrandr | grep "DP-2" | grep -v "disconnected" )

#2 ex. Monitors
if [[ "$VGA" != "" && "$HDMI" != "" ]]; then
    xrandr --output DP-2 --auto --output HDMI-1 --auto --right-of DP-2 --output eDP-1 --off
elif [[ "$VGA" != "" ]]; then
    xrandr --output eDP-1 --auto --output DP-2 --auto --same-as eDP-1 --output HDMI-1 --off
elif [[ "$HDMI" != "" ]]; then
    xrandr --output eDP-1 --auto --output HDMI-1 --auto --same-as eDP-1 --output DP-2 --off
else
    xrandr --output eDP-1 --auto --output HDMI-1 --off --output DP-2 --off
fi
