#!/bin/bash

#2 ex. Monitors -> Turn off Laptop Display
#1 ex. Monitor -> Mirror Laptop
#0 ex. Monitors -> Just show Laptop

set -x

MONITOR=$(wlr-randr | sed -n 's/^\(eDP\S*\).*/\1/p')
HDMI=$(xrandr | sed -n 's/^\(HDMI\S*\) connected.*$/\1/p') #find connected HDMI, e.g. thinkpad has two (disconnected) HDMI names
VGA=$(wlr-randr | sed -n 's/^\(DP-[0-9]\).*/\1/p') #find connected HDMI, e.g. thinkpad has two (disconnected) HDMI names
#2 ex. Monitors
if [[ "$VGA" != "" && "$HDMI" != "" ]]; then
    xrandr --output $VGA --auto --output $HDMI --auto --right-of $VGA --output $MONITOR --off
elif [[ "$VGA" != "" ]]; then
    #xrandr --output $MONITOR --auto --off --output $VGA --auto --same-as $MONITOR --output $HDMI --off
# Cant mirror monitor    wlr-randr --output $VGA --on --pos 0,0 --output $MONITOR --on --pos 0,0
  wlr-randr --output $VGA --on --pos 0,0 --output $MONITOR --off
elif [[ "$HDMI" != "" ]]; then
    xrandr --output $MONITOR --auto --output $HDMI --auto --same-as $MONITOR #--output $VGA --off
else
    wlr-randr --output $MONITOR --on --pos 0,0
fi
