#!/bin/sh
#Enable Capslock LED if microphone is off
#xset does not fail even if caps lock does not have an LED
amixer -q -D pulse sset Capture toggle
MICROPHONEOFF=$(amixer -q -D pulse scontents Capture | tail -n 1 | sed -n 's/.*off.*/off/p' )
if [[ "$MICROPHONEOFF" == "off" ]]; then
  xset led named 'Caps Lock'
else
  xset -led named 'Caps Lock'
fi
