#!/bin/sh
#Used for vim compile latex

set -e #So dont show PDF when compilation broke (Also on first time generate PDF)

FILEPATHWOEXT="$1"

/bin/pdflatex -output-directory '/tmp' "$FILEPATHWOEXT.tex" 

ALREADYSHOWN=$(pgrep -f "$FILEPATHWOEXT.pdf" || true ) #-f also searches inside processes arguments names (important for pdf), || true because empty pgrep exits 1
if [[ "$ALREADYSHOWN" == "" ]] ; then
  zathura "$FILEPATHWOEXT.pdf" &
fi
