#!/bin/sh

set -e
TMP=$(mktemp -d)
cd $TMP
youtube-dl -f m4a $@;

for i in *.m4a; do
    echo "$i"
    read -p "Interpret: " INTERPRET
    read -p "Title: " TITLE
    mv "$i" "${INTERPRET// /_}_-_${TITLE// /_}.m4a"
done

mkdir -p name
for f in *.m4a; do mv -- "$f" "name/${f//\ /_}"; done

cd name
for i in *.m4a; do
    POSTFIXFREE=`echo $i | cut -d'.' -f1`;
    INTERPRET=$(echo $i  | awk -F"_-" '{print $1}' | sed 's/_/\ /g')
    TITLE=$(echo -n $i | awk -F"-" '{print $2}' | cut -c 2- | awk -F"." '{print $1}' | sed 's/_/\ /g')
    
    ffmpeg -i "$i" -metadata artist="$INTERPRET" -metadata title="$TITLE" $POSTFIXFREE.mp3;
    trash "$i";
done

for f in *.mp3; do mv -- "$f" "${f//_/ }"; done
mkdir -p ~/MusikDownloads;
mv *.mp3 ~/MusikDownloads;
